// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto // import "raft_grpc/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenerateIDRequest struct {
	LastID               int64    `protobuf:"varint,1,opt,name=lastID,proto3" json:"lastID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateIDRequest) Reset()         { *m = GenerateIDRequest{} }
func (m *GenerateIDRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateIDRequest) ProtoMessage()    {}
func (*GenerateIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_1510f931ef25bb47, []int{0}
}
func (m *GenerateIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateIDRequest.Unmarshal(m, b)
}
func (m *GenerateIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateIDRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateIDRequest.Merge(dst, src)
}
func (m *GenerateIDRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateIDRequest.Size(m)
}
func (m *GenerateIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateIDRequest proto.InternalMessageInfo

func (m *GenerateIDRequest) GetLastID() int64 {
	if m != nil {
		return m.LastID
	}
	return 0
}

type GenerateIDResponse struct {
	NewID                int64    `protobuf:"varint,1,opt,name=newID,proto3" json:"newID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateIDResponse) Reset()         { *m = GenerateIDResponse{} }
func (m *GenerateIDResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateIDResponse) ProtoMessage()    {}
func (*GenerateIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_1510f931ef25bb47, []int{1}
}
func (m *GenerateIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateIDResponse.Unmarshal(m, b)
}
func (m *GenerateIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateIDResponse.Marshal(b, m, deterministic)
}
func (dst *GenerateIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateIDResponse.Merge(dst, src)
}
func (m *GenerateIDResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateIDResponse.Size(m)
}
func (m *GenerateIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateIDResponse proto.InternalMessageInfo

func (m *GenerateIDResponse) GetNewID() int64 {
	if m != nil {
		return m.NewID
	}
	return 0
}

func init() {
	proto.RegisterType((*GenerateIDRequest)(nil), "GenerateIDRequest")
	proto.RegisterType((*GenerateIDResponse)(nil), "GenerateIDResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_1510f931ef25bb47) }

var fileDescriptor_service_1510f931ef25bb47 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe6, 0x12, 0x74, 0x4f, 0xcd,
	0x4b, 0x2d, 0x4a, 0x2c, 0x49, 0xf5, 0x74, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12,
	0xe3, 0x62, 0xcb, 0x49, 0x2c, 0x2e, 0xf1, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82,
	0xf2, 0x94, 0xb4, 0xb8, 0x84, 0x90, 0x15, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x70,
	0xb1, 0xe6, 0xa5, 0x96, 0xc3, 0x15, 0x43, 0x38, 0x46, 0x2e, 0x5c, 0xdc, 0x41, 0x89, 0x69, 0x25,
	0xc1, 0x10, 0xdb, 0x84, 0x4c, 0xb9, 0xb8, 0x10, 0x5a, 0x85, 0x84, 0xf4, 0x30, 0x2c, 0x95, 0x12,
	0xd6, 0xc3, 0x34, 0xdb, 0x49, 0x30, 0x8a, 0xbf, 0x28, 0x31, 0xad, 0x24, 0x3e, 0xbd, 0xa8, 0x20,
	0x59, 0x1f, 0xec, 0xe2, 0x24, 0x36, 0x30, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x24,
	0xaa, 0xc4, 0xc9, 0x00, 0x00, 0x00,
}
